apiVersion: v1
kind: Namespace
metadata:
  name: console

root@master:/opt/manifests/okd# cat 02_okd.yml 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: skooner-cluster-admin
subjects:
  - kind: ServiceAccount
    name: okd-console-openshift-console 
    namespace: console
roleRef:
  apiGroup: rbac.authorization.k8s.io   
  kind: ClusterRole
  name: admin
